### PR TITLE
Let ActiveRecord sort out proper limit

### PR DESCRIPTION
**Pull request by crdunwel**
See https://github.com/EFForg/phantom-of-the-capitol/issues/81 for details.

### CODE REVIEW

**Comment by crdunwel** [comment]
Any thing preventing this from being merged?

**Comment by TheNotary** [comment]
Hi crdunwel,

First, thanks for the PR!  The primary maintainer for this app is passing that obligation over to me, but I'm not fully read up on the material to make autonomous changes.  

From my standpoint, all of those `limit` definitions that show up in the schema.rb seem random.  I don't know some are needed now, or if any of them were ever deliberate in the first place.  Regardless of why, we should at the very least justify their existence in the `db/migrate` as a matter of etiquette.  That said I see two path's forward:

a)  Completely rebuild the schema.rb using `rake db:migrate` after dropping the database on a dev machine
OR
b)  Add a migration script to add those `limit` definitions to the database where desirable, and then rebuild the schema.rb using `padrino rake ar:migrate`

Does that sound reasonable, and are you in a position to give it a try?

**Comment by crdunwel** [comment]
Sorry, my lack of familiarity with padrino and active record is showing. I believe that the issue may be that the [dev setup script](https://github.com/EFForg/phantom-of-the-capitol/blob/master/setup_dev.sh#L53) is loading the versioned schema file without generating the adapter-specific schema from scratch [as intended](https://github.com/EFForg/phantom-of-the-capitol/blob/master/db/schema.rb#L6). The schema file generated with the postgresql adapter looks a bit different and may be incompatible with mysql, but, aside from limit on boolean fields, postgresql doesn't have any issues with the mysql generated schema.

I can create a migration file to remove the limit, but anybody rolling back with postgres will likely get a syntax error in the SQL. The schema can be built from scratch so this isn't a huge issue but it does cause an extra step in setting up a development environment with vagrant / docker. Really not a huge deal in any case. Perhaps altering the setup scripts to rebuild the schema from scratch may be a better alternative?

**Comment by Hainish** [comment]
@crdunwel I'm confused what you mean by "rebuild the schema from scratch" since that seems to be what it's already doing with the `ar:schema:load`...

I'm fine with removing the limits generally, not really sure why they're there in the first place.  Maybe it's padrino's way to by default have limits when `add_column` is issued or something.  I'm fine with merging this, and can get to it tomorrow

**Comment by crdunwel** [comment]
@Hainish Yeah looking back I may have missed a step in creating the schema from scratch. Probably somewhere between setting up locally with [setup_dev.sh](https://github.com/EFForg/phantom-of-the-capitol/blob/master/setup_dev.sh) and production using PostgreSQL. Sorry for trouble y'all!

**Pull request closed without merging**
