### PR TITLE
Allow message delivery via Communicating With Congress

### PR DESCRIPTION
**Pull request by wioux**
This branch expands the app to support delivering messages via the Communicating with Congress (CWC) API. All voting representatives in the House as well as almost all non-voting reps can be messaged via this API, and it is currently the most viable way of delivering messages to congress due to difficulties we have confronting reCAPTCHA challenges.

To enable the new delivery mechanism you must [apply to become a vendor](http://www.house.gov/content/vendors/cwc/) and then [provide these environment variables](https://github.com/EFForg/phantom-of-the-capitol/blob/cwc/config/phantom-dc_config.rb.example#L18-L26):

  * CWC_API_KEY
  * CWC_HOST -- e.g. https://test-cwc.house.gov/
  * CWC_DELIVERY_AGENT -- delivery agent name, must match API key owner
  * CWC_DELIVERY_AGENT_ACK_EMAIL
  * CWC_DELIVERY_AGENT_CONTACT_NAME
  * CWC_DELIVERY_AGENT_CONTACT_EMAIL
  * CWC_DELIVERY_AGENT_CONTACT_PHONE

The new functionality is such that clients should not have to change much, with one exception. A new message field for `POST /fill-out-form` requests is introduced, `$STATEMENT`. Clients must use this field instead of `$MESSAGE` if the message was not truly authored by an individual constituent but is instead the statement of an advocacy organization, or suggested text, etc.

### CODE REVIEW

**Comment by wioux** [comment]
Awesome. Ok, just reverting a change I pushed last week that on second thought wasn't necessary...

Looking forward to seeing the enhancements. Thanks!

**Comment by oregondean** [comment]
I've applied for CWC access and look forward to the increased efficiency of contacting the House members via this gateway.  Is there anything similar underway on the Senate side?

**Comment by j-ro** [comment]
The Senate does not implement CWC, and has no API at all that I know of, so no, not until that changes.

**Comment by oregondean** [comment]
Thanks for that quick reply.  I am not afraid to start to move the Senate in this direction.  Do you know who was behind the House's implementation?

**Comment by j-ro** [comment]
It was an internal project of the House itself, as far as I know, with obvious collaboration with the various CRM vendors the House uses. Good luck on the Senate -- all Senate web infrastructure is run and controlled by the Sergeant at Arms, and they generally only look inside the institution for guidance and instruction. Which means that the only way this gets done on the Senate side is if the Senate itself leads. As far as I can tell, there's not much outsiders can do to push the point.

**Comment by joelcollinsdc** [comment]
Glad to see this landed!  I think it was actually a long process, the Congressional Management Foundation did a lot of the early work.  

BTW #79 can be closed now.

**Pull request merged**
